name: vdm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - pip:
      - tqdm
      - accelerate==0.16.0
      - black==23.1.0
      - ema-pytorch==0.1.4
      - isort==5.12.0
      - numpy==1.24.2
      - Pillow==9.4.0
      - PyYAML==6.0
      - torch==2.5.1
      - torchinfo
      - torchvision
      - gdown
